In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import tensorflow as tf
import librosa
from librosa import display
%matplotlib inline

##Read X

In [16]:
os.getcwd()

'/content'

In [17]:
ls

drive/  sample_data/


In [18]:
xtestpath = '/content/drive/MyDrive/COLAB Files/test/X'

In [19]:
os.chdir(xtestpath)
os.getcwd()

'/content/drive/.shortcut-targets-by-id/1fsWPymjqm8TR_nz5KqB4_FnuN4elb1w5/test/X'

In [20]:
xp = os.listdir()
len(xp)

2500

In [21]:
x_test = np.zeros((len(xp),64,1000,1))

for i in range(len(xp)):
  a = np.load(xp[i])
  x_test[i,:,0:1000,0] = a[0,:,0:1000]

In [22]:
x_test.shape 

(2500, 64, 1000, 1)

In [23]:
xp[0]

'melspec_20.npy'

In [24]:
type(x_test)

numpy.ndarray

#Pred

In [25]:
m = tf.keras.models.load_model('/content/drive/MyDrive/COLAB Files/cnn1')

In [26]:
y_pred = m.predict(x_test)

79/79 [==============================] - 22s 278ms/step


In [27]:
for i in range (len(y_pred)) :
  for j in range (10):
    if y_pred[i,j] >=0.5 :
      y_pred[i,j] = 1
    else :
      y_pred[i,j] = 0

In [28]:
y_pred[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [29]:
y_pred = y_pred.astype(int)

In [30]:
y_pred

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [31]:
y_pred[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [32]:
df = pd.DataFrame(y_pred, columns = [    
    'Alarm_bell_ringing', 
    'Blender', 
    'Cat', 
    'Dishes', 
    'Dog',
    'Electric_shaver_toothbrush', 
    'Frying', 
    'Running_water',
    'Speech', 
    'Vacuum_cleaner'])

In [33]:
df

Alarm_bell_ringing  Blender  Cat  Dishes  Dog  \
0                      0        0    0       0    0   
1                      0        0    0       0    0   
2                      0        0    0       0    0   
3                      0        0    0       0    0   
4                      0        0    0       0    0   
...                  ...      ...  ...     ...  ...   
2495                   0        0    0       0    0   
2496                   0        0    0       0    0   
2497                   0        0    0       0    0   
2498                   0        0    0       0    0   
2499                   0        0    0       0    0   

      Electric_shaver_toothbrush  Frying  Running_water  Speech  \
0                              0       0              0       1   
1                              0       0              0       1   
2                              0       0              0       1   
3                              0       0              0       1   
4                              0       0              0       1   
...                          ...     ...            ...     ...   
2495                           0       0              0       1   
2496                           0       0              0       1   
2497                           0       0              0       1   
2498                           0       0              0       1   
2499                           0       0              0       1   

      Vacuum_cleaner  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
2495               0  
2496               0  
2497               0  
2498               0  
2499               0  

[2500 rows x 10 columns]

In [34]:
dfxp = pd.DataFrame(xp, columns = ['fileid'])

In [35]:
dfxp

fileid
0       melspec_20.npy
1      melspec_113.npy
2     melspec_2200.npy
3     melspec_1611.npy
4      melspec_787.npy
...                ...
2495   melspec_478.npy
2496  melspec_1584.npy
2497   melspec_795.npy
2498  melspec_1510.npy
2499  melspec_1566.npy

[2500 rows x 1 columns]

In [36]:
final = pd.concat([dfxp,df], axis=1)

In [37]:
final

fileid  Alarm_bell_ringing  Blender  Cat  Dishes  Dog  \
0       melspec_20.npy                   0        0    0       0    0   
1      melspec_113.npy                   0        0    0       0    0   
2     melspec_2200.npy                   0        0    0       0    0   
3     melspec_1611.npy                   0        0    0       0    0   
4      melspec_787.npy                   0        0    0       0    0   
...                ...                 ...      ...  ...     ...  ...   
2495   melspec_478.npy                   0        0    0       0    0   
2496  melspec_1584.npy                   0        0    0       0    0   
2497   melspec_795.npy                   0        0    0       0    0   
2498  melspec_1510.npy                   0        0    0       0    0   
2499  melspec_1566.npy                   0        0    0       0    0   

      Electric_shaver_toothbrush  Frying  Running_water  Speech  \
0                              0       0              0       1   
1                              0       0              0       1   
2                              0       0              0       1   
3                              0       0              0       1   
4                              0       0              0       1   
...                          ...     ...            ...     ...   
2495                           0       0              0       1   
2496                           0       0              0       1   
2497                           0       0              0       1   
2498                           0       0              0       1   
2499                           0       0              0       1   

      Vacuum_cleaner  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
2495               0  
2496               0  
2497               0  
2498               0  
2499               0  

[2500 rows x 11 columns]

In [38]:
final.to_csv(r'/content/drive/MyDrive/final_cnn_pred.csv', index=False, header=True)