In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import tensorflow as tf
import librosa
from librosa import display
%matplotlib inline

#Loading

In [2]:
path = '/content/drive/MyDrive/COLAB Files/dataset_a2'

In [3]:
x_train = np.load('/content/drive/MyDrive/COLAB Files/dataset_a2/x_train.npy')

In [4]:
x_test = np.load('/content/drive/MyDrive/COLAB Files/dataset_a2/x_test.npy')

In [5]:
y_train = np.load('/content/drive/MyDrive/COLAB Files/dataset_a2/y_train.npy')

In [6]:
y_test = np.load('/content/drive/MyDrive/COLAB Files/dataset_a2/y_test.npy')

In [9]:
x_train.shape

(8000, 64, 1000, 1)

In [10]:
y_train.shape

(8000, 10)

In [11]:
x_test.shape

(2000, 64, 1000, 1)

In [12]:
y_test.shape

(2000, 10)

In [49]:
y_train[0]

array([0., 0., 0., 1., 0., 0., 1., 0., 1., 0.])

In [50]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1.])

In [15]:
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Conv2D, Flatten, MaxPooling2D
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.layers import Dense,Dropout,Activation
from sklearn import metrics
from tensorflow import keras
from keras.layers import Bidirectional, TimeDistributed,SpatialDropout2D, MaxPool2D, Input, GRU, LSTM,Dense, Activation, Dropout,Flatten, Reshape, Permute
from keras.layers import BatchNormalization,ZeroPadding1D
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.metrics import f1_score,recall_score,precision_score

#Model

In [22]:
m = Sequential()
m.add(Conv2D(4, (3, 3), activation='relu', input_shape=(64,1000,1)))
m.add(BatchNormalization())
m.add(MaxPooling2D((2, 2)))
m.add(Dropout(0.25))

m.add(Conv2D(16, (3, 3), activation='relu'))
m.add(BatchNormalization())
m.add(MaxPooling2D((2, 2)))
m.add(Dropout(0.25))

m.add(Conv2D(64, (3, 3), activation='relu'))
m.add(BatchNormalization())
m.add(MaxPooling2D((2, 2)))
m.add(Dropout(0.25))

m.add(Flatten())
m.add(Dense(128, activation='relu'))
m.add(Dropout(0.25))
m.add(Dense(10, activation='sigmoid'))

m.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 998, 4)        40        
                                                                 
 batch_normalization (BatchN  (None, 62, 998, 4)       16        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 31, 499, 4)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 31, 499, 4)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 497, 16)       592       
                                                                 
 batch_normalization_1 (Batc  (None, 29, 497, 16)      6

In [23]:
m.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
m.fit(x_train, y_train, epochs=200)

#pred

In [54]:
y_pred = m.predict(x_test)

63/63 [==============================] - 1s 10ms/step


In [55]:
print(y_test[0])
print(y_pred[0])

[0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
[0.08600029 0.13986954 0.10861553 0.38920778 0.12266248 0.12388919
 0.21290597 0.14065251 0.8863853  0.0578765 ]


In [59]:
for i in range (len(y_pred)) :
  for j in range (10):
    if y_pred[i,j] >=0.5 :
      y_pred[i,j] = 1
    else :
      y_pred[i,j] = 0

In [61]:
print(f1_score(y_test, y_pred, average = 'micro'))

0.5805837563451776


In [67]:
os.getcwd()

'/content'

In [69]:
path = '/content/drive/MyDrive/COLAB Files'
os.chdir(path)
os.getcwd()

'/content/drive/MyDrive/COLAB Files'

In [71]:
m.save('cnn1')