In [69]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import tensorflow as tf
import librosa
%matplotlib inline

##Load test_labels

In [71]:
path = '/content/drive/MyDrive/lables_test'
os.chdir(path)
os.getcwd()

'/content/drive/MyDrive/lables_test'

In [72]:
def eventroll_to_multihot_vector(eventroll):
    """
    Parameters
    ----------
    eventroll : np.array
        Eventroll matrix of shape=(11, 1000).
    
    Returns
    -------
    np.array
        A multihot vector of shape=(10,)
    """
    
    # findout active events:
    active_events = (eventroll.sum(axis=1) >= 0.5).astype('float')
    
    # remove silence class:
    return np.delete(active_events, 8)

In [73]:
os.chdir(path)
os.getcwd()

'/content/drive/MyDrive/lables_test'

In [74]:
yp = os.listdir()
len(yp)

2500

In [75]:
yp[0]

'eventroll_2348.npy'

In [76]:
yp.sort()

In [77]:
yp[0]

'eventroll_0.npy'

In [78]:
y_et = np.zeros((len(yp),11,1000))

for i in range(len(yp)):
  b = np.load(yp[i])
  y_et[i,:,:] = b[:,:]

In [79]:
y = np.zeros((len(yp),10))

for i in range(len(yp)):
  c = eventroll_to_multihot_vector(y_et[i])
  y[i,:] = c

In [80]:
y.shape

(2500, 10)

In [81]:
y[0].shape

(10,)

In [82]:
y[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 1., 0.])

In [83]:
y_test = y

##Read X

In [84]:
os.getcwd()

'/content/drive/MyDrive/lables_test'

In [85]:
xtestpath = '/content/drive/MyDrive/test/X'

In [86]:
os.chdir(xtestpath)
os.getcwd()

'/content/drive/MyDrive/test/X'

In [87]:
xp = os.listdir()
len(xp)

2500

In [88]:
xp[0]

'melspec_20.npy'

In [89]:
xp.sort()

In [90]:
xp[0]

'melspec_0.npy'

In [91]:
x_test = np.zeros((len(xp),64,1000,1))

for i in range(len(xp)):
  a = np.load(xp[i])
  x_test[i,:,0:1000,0] = a[0,:,0:1000]

In [92]:
x_test.shape 

(2500, 64, 1000, 1)

In [93]:
xp[0]

'melspec_0.npy'

In [94]:
type(x_test)

numpy.ndarray

#Pred

In [95]:
m = tf.keras.models.load_model('/content/drive/MyDrive/ann')

In [96]:
y_pred = m.predict(x_test)

79/79 [==============================] - 0s 5ms/step


In [97]:
for i in range (len(y_pred)) :
  for j in range (10):
    if y_pred[i,j] >=0.5 :
      y_pred[i,j] = 1
    else :
      y_pred[i,j] = 0

In [98]:
y_pred[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 0.], dtype=float32)

In [99]:
y_pred = y_pred.astype(int)

In [100]:
y_pred

array([[0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [101]:
y_pred[0]

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

#F1score

In [110]:
from sklearn.metrics import f1_score,recall_score,precision_score

In [112]:
print(f1_score(y_test,y_pred,average='samples'))

0.4831923809523809


#Recall

In [114]:
print(recall_score(y_test,y_pred,average='samples'))

0.46749714285714283


#Precision

In [116]:
print(precision_score(y_test,y_pred,average='samples'))

0.5544133333333333


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Confusion Matrix

In [117]:
from sklearn.metrics import confusion_matrix
for i in range(10) :
  print(confusion_matrix(y_test[:,i], y_pred[:,i]))

[[1910  190]
 [ 366   34]]
[[1800  434]
 [ 208   58]]
[[2078  138]
 [ 261   23]]
[[1272  539]
 [ 504  185]]
[[2040  119]
 [ 316   25]]
[[2088  129]
 [ 263   20]]
[[1820  303]
 [ 352   25]]
[[1964  230]
 [ 274   32]]
[[  10  117]
 [ 222 2151]]
[[2098  151]
 [ 228   23]]
