In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import tensorflow as tf
import librosa
%matplotlib inline

##Read X

In [3]:
os.getcwd()

'/content'

In [4]:
ls

drive/  sample_data/


In [5]:
xtestpath = '/content/drive/MyDrive/test/X'

In [6]:
os.chdir(xtestpath)
os.getcwd()

'/content/drive/MyDrive/test/X'

In [7]:
xp = os.listdir()
len(xp)

2500

In [8]:
x_test = np.zeros((len(xp),64,1000,1))

for i in range(len(xp)):
  a = np.load(xp[i])
  x_test[i,:,0:1000,0] = a[0,:,0:1000]

In [9]:
x_test.shape 

(2500, 64, 1000, 1)

In [10]:
xp[0]

'melspec_1351.npy'

In [11]:
type(x_test)

numpy.ndarray

#Pred

In [12]:
m = tf.keras.models.load_model('/content/drive/MyDrive/ann')

In [13]:
y_pred = m.predict(x_test)

79/79 [==============================] - 1s 8ms/step


In [14]:
for i in range (len(y_pred)) :
  for j in range (10):
    if y_pred[i,j] >=0.5 :
      y_pred[i,j] = 1
    else :
      y_pred[i,j] = 0

In [15]:
y_pred[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [17]:
y_pred = y_pred.astype(int)

In [19]:
y_pred

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0]])

In [18]:
y_pred[0]

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [20]:
df = pd.DataFrame(y_pred, columns = [    
    'Alarm_bell_ringing', 
    'Blender', 
    'Cat', 
    'Dishes', 
    'Dog',
    'Electric_shaver_toothbrush', 
    'Frying', 
    'Running_water',
    'Speech', 
    'Vacuum_cleaner'])

In [21]:
df

Alarm_bell_ringing  Blender  Cat  Dishes  Dog  \
0                      0        0    0       1    0   
1                      0        0    0       0    0   
2                      0        0    0       0    1   
3                      0        0    0       0    0   
4                      0        0    0       0    0   
...                  ...      ...  ...     ...  ...   
2495                   0        0    0       0    0   
2496                   0        0    0       1    0   
2497                   0        0    0       1    0   
2498                   0        0    0       0    0   
2499                   0        0    0       1    0   

      Electric_shaver_toothbrush  Frying  Running_water  Speech  \
0                              0       0              0       1   
1                              1       0              0       0   
2                              0       0              0       1   
3                              0       0              1       1   
4                              0       0              0       0   
...                          ...     ...            ...     ...   
2495                           0       0              0       1   
2496                           0       1              0       1   
2497                           0       0              0       1   
2498                           0       0              0       1   
2499                           0       0              1       1   

      Vacuum_cleaner  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
2495               0  
2496               0  
2497               0  
2498               0  
2499               0  

[2500 rows x 10 columns]

In [22]:
dfxp = pd.DataFrame(xp, columns = ['fileid'])

In [23]:
dfxp

fileid
0     melspec_1351.npy
1     melspec_1356.npy
2     melspec_1355.npy
3     melspec_1354.npy
4      melspec_135.npy
...                ...
2495   melspec_988.npy
2496   melspec_984.npy
2497   melspec_983.npy
2498    melspec_99.npy
2499   melspec_985.npy

[2500 rows x 1 columns]

In [24]:
final = pd.concat([dfxp,df], axis=1)

In [25]:
final

fileid  Alarm_bell_ringing  Blender  Cat  Dishes  Dog  \
0     melspec_1351.npy                   0        0    0       1    0   
1     melspec_1356.npy                   0        0    0       0    0   
2     melspec_1355.npy                   0        0    0       0    1   
3     melspec_1354.npy                   0        0    0       0    0   
4      melspec_135.npy                   0        0    0       0    0   
...                ...                 ...      ...  ...     ...  ...   
2495   melspec_988.npy                   0        0    0       0    0   
2496   melspec_984.npy                   0        0    0       1    0   
2497   melspec_983.npy                   0        0    0       1    0   
2498    melspec_99.npy                   0        0    0       0    0   
2499   melspec_985.npy                   0        0    0       1    0   

      Electric_shaver_toothbrush  Frying  Running_water  Speech  \
0                              0       0              0       1   
1                              1       0              0       0   
2                              0       0              0       1   
3                              0       0              1       1   
4                              0       0              0       0   
...                          ...     ...            ...     ...   
2495                           0       0              0       1   
2496                           0       1              0       1   
2497                           0       0              0       1   
2498                           0       0              0       1   
2499                           0       0              1       1   

      Vacuum_cleaner  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
2495               0  
2496               0  
2497               0  
2498               0  
2499               0  

[2500 rows x 11 columns]

In [27]:
final.to_csv(r'/content/drive/MyDrive/final_ann_pred.csv', index=False, header=True)